name: Reusable CI Tests

on:
  workflow_call: {}

jobs:
  test-server:
    name: Test Go Server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"

      - name: Install dependencies
        run: |
          cd server
          go mod tidy

      - name: Run tests
        run: |
          cd server
          go test ./... -v
